### PR TITLE
<: -- convenience operator to facilitate literal-ish syntax for TypeMaps

### PR DESCRIPTION
**Pull request by deepfire**
Notes:

1. No opinion on how the operator should look like
2. Maybe a different fixity?
3. The Alt-version still being ironed out in CI

### CODE REVIEW

**Comment by Lysxia** [comment]
Thanks! That looks good. I'll merge if Travis says OK and prepare a release in a week or so.

**Comment by deepfire** [comment]
@Lysxia, unfortunately https://ghc.haskell.org/trac/ghc/ticket/12363 effectively prevents this syntactic shortcut for the `Dynamic.Alt` version, so had to roll it back.

**Comment by Lysxia** [comment]
I see, thanks for looking into it. I think we can still export the same operator from `Alt` even if it can't be type-applied. We could also add a function `at :: forall t a. a -> (Proxy t, a) ; at = (,) Proxy` so this is possible: `m <: at @foo 33`.

Thanks also for adding `.gitignore`. I have a `$HOME/.gitignore` for common ignores, which is why there wasn't one at the start, but it doesn't hurt to have one in the repo, if it makes anyone's life easier.

Tell me once you're ready to merge!

**Comment by deepfire** [comment]
@Lysxia, I think it's done now : -)

**Comment by deepfire** [comment]
(..pushed indentation fix)

**Comment by Lysxia** [comment]
Great, thanks!

**Pull request merged**
